Fix compiler errors with -O0 -fopenmp and Eigen
Optimization in openmp-vectorize.patch:

 --- gcc-5.3.0/gcc/opts.c.org    2016-01-01 15:08:15.128087498 -0500
 +++ gcc-5.3.0/gcc/opts.c    2016-01-01 15:10:39.273285435 -0500
 @@ -669,6 +669,16 @@
  {
    enum unwind_info_type ui_except;

 +  /* openmp to imply tree vectorize */
 +  if (opts->x_flag_openmp) {
 +   opts->x_flag_tree_vectorize = 1;
 +       opts->x_flag_tree_loop_vectorize = 1;
 +   opts->x_optimize = 3;
 +   opts->x_flag_gcse_after_reload = 1;
 +   opts->x_flag_dse = 1;
 +   opts->x_flag_schedule_insns = 1;
 +  }
 +

creates a bug if the vectorization is not enable at all when users are
building with -O0 -fopenmp in Eigen code:

    /usr/lib64/gcc/x86_64-generic-linux/7.2.1/include/tmmintrin.h:188:32:
    error: the last argument must be an 8-bit immediate (__v2di)__Y, __N *
    8);

Deeper solution is needed but this is the patch that creates the
bug. Remove this patch might impact performance numbers, but external
users are being afected right now because of this patch

Signed-off-by: Victor Rodriguez <victor.rodriguez.bahena@intel.com>